### PR TITLE
Features/typo symbol filtering

### PR DESCRIPTION
**Pull request by robLittiere**
Hello, 

We added a functionnality that allows the user to dynamically choose which pictogram they wish to display or to hide by checking a checkbox on the pictogram display menu.
Magrit will then only draw checked pictograms on the layer.

We made it as a quality of life improvement as we sometimes felt like we didnt to display all fields from our data but only selected ones. By default, all fields are selected and thus, we keep magrit's default behaviour

You can see a render exemple in the screenshot below

Capture d’écran du 2023-03-16 11-55-07

### CODE REVIEW

**Comment by mthh** [comment]
Hello @robLittiere

Thank you very much for this valuable contribution!

I glanced at the code and started to try this new feature. Overall it looks good but I noticed a few things:

- pictograms that are not displayed on the map still appear in the legend, I think that this is not desirable,

- this new feature has not been integrated into the code that saves the project as a project file, nor has it been integrated into the code that reloads the project file - in the [client/js/map_project.js](https://github.com/riatelab/magrit/blob/master/client/js/map_project.js) file), so currently when we try to reload a project with symbols filtered by your method, various error messages appear in the console and the reload operation fails.

Could you take care of these two points?
(the legend code and the project-file save/reload code are pretty messy, so feel free to ask if you need guidance or if you want me to take care of it)

**Comment by robLittiere** [comment]
Hello @mthh 

Thank you for your quick feedback, indeed, we absolutly forgot about legend and project save/load ! Thank you for bringing this up.

What has been done after some time to understand how the project save/load flow work 😄  

-  I modified the way we were filtering symbols so we actually filter the list of symbol_map that magrit uses to render its symbols. This way, Magrit actually generates the correct legend by itself.

- I added the necessary so we save the list of desired filtered symbols upon saving a project whether it is saved manually or on local storage, I think it uses the same logic so both work. 

- Upon loading, we can get the previously saved list of filtered symbols so we can filter again when we project the symbol layer.

If other bugs are encountered, please let me know !

**Comment by mthh** [comment]
Thanks, I tested it and most of it seems to work.
Overall the code looks good to me and I see that you seem to have found your way around Magrit's code :sweat_smile: 

There is one last detail though.

The scenario is : the user selects his symbols before creating a layer (let's say we use the Brazil layer as in your example, and we deactivate 2 of the 5 categories - see my first screenshot) and then clicks on "confirmation", the window closes.
If the user reopens the symbol selection window, he/she will now only see the selected categories, the others have completely disappeared (see my second screenshot).

- Ideally, he should find the window as he left it (with the same categories deselected)
- Otherwise, I'm also OK with the fact that he finds the window in its initial state (all categories displayed).

**Comment by robLittiere** [comment]
Thanks for your feedback, finding where to put the correct lines was not easy but it is done ! 👍 

Your scenario is correct and is exactly what we imagined, however the issue you pointed is most definitly an unwanted behaviour, we would like at least to be able to check/uncheck all categories again. I'll see what I can do

**Comment by robLittiere** [comment]
What has been done in the latest commit : 

I gathered that we were actually ovewriting the symbol_map that was used to know which symbols should be showed or not. The problem was that Magrit uses this same map in "rendering_params" to let us know which fields are available for a category.
And so it created the problem where if you selected twice "choose symbols", the second time you would have only parts of the actually availabele fields.

In order to fix this, we have two solutions : 

- Add a field to rendering_params object that would only be used to list available fields for a category.

- Don't modify the symbol_map variable and leave it as it is, although we would need to add another variable that contains the actual map of symbols to display.  

Both solutions have the same effect, the first would maybe have been simpler to integrate.
As I could not find where the rendering_params were initially set or how it worked 😞 , I went with the second solution.

Which means I had to modify the naming variables in the legend, save/export/load code for projecting TypoSymbol layers. Instead of using the symbol_map property from the data_manager, we use its symbol_to_display property.

> - Ideally, the user should find the window as he/she left it (with the same categories deselected) 
> - Otherwise, I'm also OK with the fact that the user finds the window in its initial state (all categories displayed).

For now, I have left it as default behaviour, when you click on "choose symbols" again, you will get everything checked.
To make it better, indeed we could save a state of the checkboxes in the rendering_params (since its used for the displaybox) or elsewhere) to which fields were checked or unchecked. We will try to take the time to implement it for sure !

**Comment by mthh** [comment]
Thanks a lot !
I pulled your last changes and I played a bit with the new functionality, that's great :+1: 

I will finish to review it and merge it on Monday.

**Comment by robLittiere** [comment]
Alright, thanks for taking the time !

Let us know if there are further changes to make 👍

**Comment by robLittiere** [comment]
Hello @mthh 

I have checked the changes and commits you made

Thank you for fixing the the bugs you found.

Indeed, having all those empty images in the DOM was a mistake, thanks for fixing it.
You probably saw my big comment stating that it would be a better solution but I was scared of breaking something if we removed the whole objects 🤣 

Thank you for your feedback, don't hesitate to come back to me or @ArmelVidali (who also contributed) for further improvements 👍

**Comment by mthh** [comment]
I released version 0.14.0 with those changes. It will be made available during the night on https://magrit.cnrs.fr/ server.

**Comment by ArmelVidali** [comment]
Great !

**Pull request merged**
