### PR TITLE
Add a SQL-like Group By when joining data

### PR DESCRIPTION
**Pull request by ArmelVidali**
Hello,

Here is a small feature to remove fields containing duplicates when joining an external dataset made with @devGuez and @robLittiere 

It reuses a function I wrote for another purpose (which is overkill for this but it might usefull to you for other things) getting unique values from the data manager for a given layer.

Since we get an error trying to join a dataset to a column with duplicates (either from the target or the external dataset), the popup now only proposes fields containing no duplicates for the join.

Here is an example with the the cities dataset from Paris region for which only the INSEE id is unique (my test shows that there are 4 duplicates for the cities name in this region, I might be wrong though)

Capture d’écran du 2023-07-18 17-10-13

### CODE REVIEW

**Comment by ArmelVidali** [comment]
I just added the same behavior for the external dataset

**Comment by ArmelVidali** [comment]
I did some changes on the feature, and added a function to reduce an external dataset provided by a user if it has duplicates, allowing him to do a "group by" join like in SQL, where he can choose the operation made on the numerical (for now) joined field : sum, mean, max and minumum computation.

When the join pop up is modify for them to choose the fields he wants to join, if his dataset has duplicates, while keeping the previous commit that only show unique fields for the target dataset.

Here is an example using data containing duplicates.

Screen Shot 2023-07-24 at 19 04 36

It probably isn't the most effective implementation, but it works with very large dataset, the largest I tried was 50.000 rows, taking about 30secs for the join, I think this might be done on the server with Python for better performance.

This feature isin't finished (translation and some fixe have to be done), but I'm sending it to ask some advice on how to replace the external dataset used in the join.

The function I made to reduce the joined dataset returns an array of object, in the same format as used in the prepare_join_on() function. 
I tried replacing the "joined_dataset" value in the data_manager, the ext_dataset in this function along with other but it doesn't seem to work : the reduce dataset is indeed joined with the computation made (for instance sum for all numerical collumns), but other fields set not to be joined (the ones which weren't selected in the join popup) are joined anyway.

Do you know how I could replace the joined dataset by my simplified one ?

thanks !

**Comment by mthh** [comment]
Hello Armel and thanks for this PR!

This feature seems very useful and powerful overall!

I do have one concern, however: the join step is a key step in the process of learning thematic cartography as we teach it; I think your functionality should eventually be placed in an "advanced" fold-out menu (as one can do in HTML with the `summary` + `details` elements for example) so as not to make the window too heavy for beginners. Or maybe even a different window ("Jointure", the current window; "Jointure avancée" the window you propose with the SQL-like Group By functionality)... although 2 different windows might be overkill!

Besides, I'll have to test this new feature carefully (because we want to avoid unpleasant surprises for the user), which won't be possible before August 16.

Regarding the first part of this PR: I like the idea of proposing only fields without duplicates for the join (given that, in fact, the join is currently refused in the event of duplicates). However, with your proposition the user may wonder why some fields are not proposed (where currently, he/she learns that there are duplicates in these fields). I still have to think about what I prefer...!
Another solution might have been to propose (for the cartographic dataset) only the fields that have been typed as identifiers (this seems to me to be more in line with Magrit's current logic, where the type of fields - stock, ratio, identifier, etc. - is used to propose the appropriate fields in the menus used to create the various cartographic representations). What do you think about this ?

Regarding your question about replacing the dataset, I was wondering if you could send me an example CSV file (like the one used in your screenshot) so that I can test the external dataset replacement in the code.

I don't think performance is too much of a problem. I'll check during my review to see if there are improvements that can be made, but I don't think it's necessary to offload it to the server (another solution might be to do it in a WebWorker to avoid making the window non-responsive if there is a lot of feature... but that won't improve calculation time).

**Comment by ArmelVidali** [comment]
I think making an adavanced menu is a good idea, we actually thought about setting a whole begginner/pro mode for magrit, which would display more or less details for every menu of the app, probably just using some `display : none`

>  However, with your proposition the user may wonder why some fields are not proposed

This could be solved with a little warning message under the menu probably. 

> Another solution might have been to propose (for the cartographic dataset) only the fields that have been typed as identifiers (this seems to me to be more in line with Magrit's current logic, where the type of fields - stock, ratio, identifier, etc

Yes it is better and shorter than what I did, I didn't saw the type_col2 function untill the end that's why I didn't used it for this purpose as well but i will

Also, I will set an `operation` menu to each joined field for more flexibility.

I'll add two example dataset to the PR, a short one with just two collumns and the large one as well

**Comment by ArmelVidali** [comment]
I added the dataset and did some further test : it doesn't work properly if a row have an empty value (I think i know where to change it), but most importantly I probably messed up something in the join because the dataset is indeed joined, but on the wrong key (department 14 gets linked to departement 52 for instance).

What i'm trying to do now it so set the join properly, and only import the fields selected by the user (for now it joins all the fields)

**Comment by mthh** [comment]
> I eventually found how to replace the dataset, and added the operation selection for each field, everything seems to work in my test.

Great !

Also, thanks for the example dataset, this will help me reviewing your contribution !

> It still needs handling empty values and css correction

No problem, I will review it when it's ready.

**Comment by ArmelVidali** [comment]
It now handles empty values, let me know if you notice a bugg.

**Comment by mthh** [comment]
I will try to review this next week, sorry for the delay.

**Comment by mthh** [comment]
I think I should admit that this pull request is not going to be merged.

We've frozen development of the current version of Magrit in order to focus firstly on fixing bugs in the existing version and secondly (and more importantly) on developing a new major version.

However, we have incorporated some of the proposals made in this PR for the next major version.

Thanks again for the effort and for your ideas :+1:

**Comment by ArmelVidali** [comment]
Good to hear ! Can't wait to see the new version

**Pull request closed without merging**
